### ISSUE TITLE
TODO list - Nov-2018

### ISSUE THREAD

**Issue by baiqiushi** [ISG-ICS/cloudberry#608]
## Website
 - [x] Frontpage icon
 - [x] Quick-Start guide
 - [x] Article links in `Pubs` and `News`

## Server maintenance
 - [x] Backup script for configuration files 
 - [x] Backup script for Website documents
 - Backup plan for raw tweets dataset from uranium
   - [ ] A backup storage plan is needed
- [x] Deploy Backup CB and TM on `ipubmed3` 
- [ ] Migrate Backup CB and TM from `ipubmed3` to an internal server (needs to be finalized)
 - Migrate Production AsterixDB from old cluster (silver machines) to new cluster (black machines)
   - [x] Deploy latest AsterixDB binary on new cluster
   - [x] Reingest whole tweets dataset into new AsterixDB cluster
   - [x] Update CB and TM on production server (ipubmed2) talking to new AsterixDB cluster
   - [x] 60M records between Feb-2016 and Mar-2016 are missing, re-ingest them.

## Development
 - [x] Merge 3 minor fix PRs
 - [x] Autocomplete proxy's apache proxy deployment and port change in the frontend code
 - Merge Yang's live tweets PR and deploy to the production server
   - [x] New issues about this live tweets feature need to be addressed
   - [x] Tune the query interval parameter to be more conservative about the delay of DB ingestion
 - Collaborate with Prof. Shuang Zhao to integrate WebGL library into Pinmap
   - [x] Implement and create PR
   - [x] Review PR and merge into master

**Comment by chenlica** [comment]
@baiqiushi should we close this issue?

**Comment by baiqiushi** [comment]
Only two tasks left unfinished, will cover them in new TODO list issue.
