### ISSUE TITLE
TODO - Apply optimizations from CoronavirusTwitterMap to TwitterMap

### ISSUE THREAD

**Issue by baiqiushi** [ISG-ICS/cloudberry#800]
- [x] (T1) Binary data transfer for Pinmap and Heatmap queries. #780 #784 
- [x] (T2) Update Noah module to use extended twitter API to include `full_text`. #801 
- [x] (T3) TwitterMap server side cache module. #783 #791 
- [x] (T4) WS/WSS configurable. #753 #778

**Comment by Yicong-Huang** [comment]
closed as finished all TODOs.
